name: Testing
on:
  push:
    branches:
      - dev
    paths:
      - '**/test.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: print
        run:
          pwd
       
