name: Testing
on:
  push:
    branches:
      - dev
    paths:
      - '**/test.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
  steps:
    -name: printing pwd
     uses: actions/checkout@v4
    
  
